### ISSUE TITLE
Additional file extension support and stand-alone file preview

### ISSUE THREAD

**Issue by s31523** [hakua-doublemoon/DoxygenPreviewer#1]
I was wondering if it is possible to support the preview of stand-alone Doxygen files (non-code files) that have just, for example, @page code in the file (with a .dox file extension.

Example:
test.dox
/**@page p1 Page 1
  @section s1 Section 1
  This is a section

*/

**Comment by hakua-doublemoon** [comment]
Thank you for your question.
You want to read .dox file?
Sorry, I can't have interest that, so I won't do it.
（すみません、それをするためのextensionではないのでやりません。ていうか今まで放置しててすみません今気づきました）
